on:
  release:
    types: [created]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run tests
        run: go test ./cmd/app -v

  releases-linux:
    name: Release Go Binary - Linux/Amd64
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.RELEASE_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: "./cmd/app"
        binary_name: "days-between"
        extra_files: README.md

  releases-windows:
    name: Release Go Binary - Windows/Amd64
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.19
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          goos: windows
          goarch: amd64
          project_path: "./cmd/app"
          binary_name: "days-between"
          extra_files: README.md

  releases-macos:
    name: Release Go Binary - MacOs/Amd64
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.19
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          goos: darwin
          goarch: amd64
          project_path: "./cmd/app"
          binary_name: "days-between"
          extra_files: README.md