on:
  release:
    types: [created]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run tests
        run: go test ./cmd/app -v

  releases-matrix:
    name: Release Go Binary
    needs: test_suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: amd64
        exclude:
          - goarch: "386"
            goos: darwin

    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.RELEASE_TOKEN }}
        goos: ${{ matrix.goarch }}
        project_path: "./cmd/app"
        binary_name: "days-between"
        extra_files: README.md