on:
  push:
    branches: [master]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run tests
      run: go test ./cmd/app -v

  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
            good: darwin

    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        gtihub_token: ${{ secrets.RELEASE_TOKEN }}
        goos: ${{ matrix.goarch }}
        project_path: "./cmd/app"
        binary_name: "days-between"
        extra_files: README.md